# Generated by Django 3.0.8 on 2020-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.IntegerField()),
                ('department', models.IntegerField()),
                ('sub0', models.IntegerField()),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
            ],
        ),
    ]
