# Generated by Django 3.0.8 on 2020-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_becometeacher_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becometeacher',
            name='sub0',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='becometeacher',
            name='sub1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='becometeacher',
            name='sub2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='becometeacher',
            name='sub3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
