# Generated by Django 3.0.8 on 2020-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200712_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='education',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
