# Generated by Django 3.1 on 2020-09-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        ('users', '0004_auto_20200822_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.becometeacher', verbose_name='Make teacher From Applications'),
        ),
    ]
