# Generated by Django 3.0.8 on 2020-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201010_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_payment_option',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
