# Generated by Django 3.0.8 on 2020-10-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201010_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Teachers'},
        ),
    ]
