# Generated by Django 3.0.8 on 2020-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('std', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('service', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('sub_code', models.IntegerField()),
                ('instruction', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('day', models.DateField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
