# Generated by Django 3.0.8 on 2020-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='other',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='project',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
