# Generated by Django 3.1 on 2020-09-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.becometeacher')),
            ],
        ),
    ]
