# Generated by Django 3.0.8 on 2020-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20200722_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='department',
            field=models.IntegerField(),
        ),
    ]
