# Generated by Django 3.1 on 2020-09-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        ('enquiry', '0002_teachermessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherMessages',
            new_name='TeacherMessage',
        ),
    ]
