# Generated by Django 3.0.8 on 2020-07-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20200722_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='other',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='project',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
