# Generated by Django 3.0.8 on 2020-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20200722_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='other',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='project',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
