# Generated by Django 3.1.1 on 2020-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_contactusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmessage',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
