# Generated by Django 3.1.1 on 2020-10-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_contactusmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermessage',
            name='reply',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
