# Generated by Django 3.0.8 on 2020-07-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20200722_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
