# Generated by Django 3.0.8 on 2020-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20200722_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='instruction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='other',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='project',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='sub_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
