# Generated by Django 3.1.1 on 2020-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_teachermessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
