# Generated by Django 3.1.1 on 2020-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_teachermessage_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='instruction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
