# Generated by Django 3.0.8 on 2020-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20200723_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='sub_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
