# Generated by Django 3.1.1 on 2020-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_auto_20201001_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='instruction',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
