# Generated by Django 3.1.2 on 2020-10-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_auto_20201001_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmessage',
            options={'verbose_name_plural': 'General ContactUs Messages(Can be seen in your email also)'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Courses Enquiry'},
        ),
        migrations.AlterModelOptions(
            name='teachermessage',
            options={'verbose_name_plural': 'Teacher Messages'},
        ),
    ]
