# Generated by Django 3.0.8 on 2020-10-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_auto_20201006_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermessage',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
