# Generated by Django 3.0.8 on 2020-07-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='sub_course',
        ),
        migrations.AddField(
            model_name='subcourses',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Courses'),
        ),
    ]
