# Generated by Django 3.0.8 on 2020-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200715_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcourses',
            name='sub_course_name',
            field=models.CharField(max_length=50),
        ),
    ]
