# Generated by Django 3.1.2 on 2020-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200903_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='active_field',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcourses',
            name='active_field',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='active_field',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
