# Generated by Django 3.1.2 on 2020-10-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201006_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
