# Generated by Django 3.0.8 on 2020-07-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200719_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('sub_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.SubCourses')),
            ],
        ),
    ]
