# Generated by Django 3.1.2 on 2020-10-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subjects_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
