export const GET_QUERIES = 'GET_QUERIES';
export const DELETE_QUERY = 'DELETE_QUERY';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const SET_DEFAULT = "SET_DEFAULT";
export const CHANGED_SUCCESS = "CHANGED_SUCCESS";
export const CHECK_SUCCESS = "CHECK_SUCCESS";
export const GOT_COURSES = "GOT_COURSES";
export const GOT_SUB_COURSES = "GOT_SUB_COURSES";
export const ENQ_POST_SUCCESS = "ENQ_POST_SUCCESS";
export const GOT_SUBJECTS = 'GOT_SUBJECTS';
export const ADDED_COURSE = 'ADDED_COURSE';
export const ADDED_MYCOURSE = 'ADDED_MYCOURSE';
export const ADDED_EVENTS = 'ADDED_EVENTS';
export const PROFILE = 'PROFILE';
export const TSYLLABUS_UPLOAD = 'TSYLLABUS_UPLOAD';

export const MATERIAL_UPLOAD_SUCCESS = 'MATERIAL_UPLOAD_SUCCESS';
export const JOB_POST_SUCCESS = 'JOB_POST_SUCCESS';
export const SET_UPLOAD_DEFAULT = 'SET_UPLOAD_DEFAULT';

export const GOT_EVENTS = "GOT_EVENTS";
export const GOT_ENR_COURSES = "GOT_ENR_COURSES";
export const SET_DEFAULT_COURSES = "SET_DEFAULT_COURSES";
export const POST_CHAT = "POST_CHAT";
export const SYLLABUS_UPLOAD = "SYLLABUS_UPLOAD";




export const MATERIAL_UPLOAD_FAIL = 'MATERIAL_UPLOAD_FAIL';
export const GOT_CHAT = 'GOT_CHAT';
export const T_GOT_CHAT = 'T_GOT_CHAT';
export const T_POST_CHAT = 'T_POST_CHAT';

export const RESET_ERROR = "RESET_ERROR";
export const CHANGED_ERROR = "CHANGED_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const CHECK_ERROR = "CHECK_ERROR";



