# Generated by Django 3.0.8 on 2020-08-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200813_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesenrolled',
            name='student',
        ),
    ]
