# Generated by Django 3.0.8 on 2020-08-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_coursesenrolled_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenrolled',
            name='completed',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
