# Generated by Django 3.0.8 on 2020-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_coursesenrolled_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenrolled',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
