# Generated by Django 3.0.8 on 2020-08-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200819_0902'),
        ('student', '0008_auto_20200818_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenrolled',
            name='teacher',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.BecomeTeacher'),
        ),
        migrations.AlterField(
            model_name='events',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.BecomeTeacher'),
        ),
    ]
