# Generated by Django 3.0.8 on 2020-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200819_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenrolled',
            name='subject_ids',
            field=models.CharField(default=[1], max_length=200),
            preserve_default=False,
        ),
    ]
