# Generated by Django 3.0.8 on 2020-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_coursesenrolled_subject_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenrolled',
            name='subject_ids',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
