# Generated by Django 3.0.8 on 2020-08-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200820_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesenrolled',
            name='subject',
        ),
    ]
