# Generated by Django 3.0.8 on 2020-08-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('student', '0012_remove_coursesenrolled_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_sub', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Subjects')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CoursesEnrolled')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_material', models.FileField(default=None, null=True, upload_to='teacher/material_for_students')),
                ('student_enrolled_subject', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.SubjectEnrolled')),
            ],
        ),
    ]
