# Generated by Django 3.1 on 2020-08-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        ('student', '0013_subjectenrolled_uploadedmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesenrolled',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.becometeacher'),
        ),
    ]
