# Generated by Django 3.1 on 2020-08-28 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0015_auto_20200824_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=2000)),
                ('msg_time', models.DateTimeField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
                ('msg_side', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.becometeacher')),
            ],
        ),
    ]
