# Generated by Django 3.1 on 2020-09-03 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0017_auto_20200831_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', models.FileField(upload_to='student/syllabus_assignemnts')),
                ('text', models.CharField(default=None, max_length=200, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursesenrolled')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.becometeacher')),
            ],
        ),
    ]
