# Generated by Django 3.1 on 2020-09-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('student', '0018_studentupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectenrolled',
            name='enrolled_sub',
            field=models.ForeignKey(blank=True, default='Check Uploads', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subjects'),
        ),
        migrations.AlterField(
            model_name='subjectenrolled',
            name='enrollment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.coursesenrolled'),
        ),
    ]
