# Generated by Django 3.1 on 2020-09-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20200903_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectenrolled',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.coursesenrolled'),
            preserve_default=False,
        ),
    ]
