# Generated by Django 3.1.2 on 2020-10-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        ('student', '0021_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesenrolled',
            name='subject_ids',
        ),
        migrations.AlterField(
            model_name='coursesenrolled',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.becometeacher'),
        ),
    ]
