# Generated by Django 3.0.8 on 2020-10-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_feedback_star_c'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Live Classes'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='anyCom',
            field=models.CharField(default=1, max_length=51, verbose_name='Any Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='techLevel',
            field=models.CharField(default=1, max_length=100, verbose_name='Technology level used in online class'),
            preserve_default=False,
        ),
    ]
