# Generated by Django 3.0.8 on 2020-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20201014_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
