# Generated by Django 3.0.8 on 2020-11-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200820_1403'),
        ('student', '0025_chatmodel_from_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenrolled',
            name='select_teachers',
            field=models.ManyToManyField(related_name='teacher_selected', to='teacher.BecomeTeacher'),
        ),
        migrations.CreateModel(
            name='selectedTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('is_selected', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CoursesEnrolled')),
                ('teacher_replied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_replied', to='teacher.BecomeTeacher')),
            ],
        ),
    ]
