# Generated by Django 3.0.8 on 2020-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20201105_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedteachers',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
