# Generated by Django 3.0.8 on 2020-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20201105_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesenrolled',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
